version: '3.8'

services:
  web:
    build:
      context: .
    environment:
      ROUTING_API_KEY: INSERT.YOUR.API.KEY.HERE
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: ruptus_3000_dev
      PGPORT: 5432
      PGHOST: postgres
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgres
    command: sh -c "mix ecto.setup && mix phx.server"
    env_file: .env
    volumes:
      - .:/app

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ruptus_3000_dev
    volumes:
      - /opt/postgres/ruptus_3000_db:/var/lib/postgresql/data
